### ISSUE TITLE
Search by ip range.

### ISSUE THREAD

**Issue by timukas** [Graylog2/graylog2-web-interface#868]
Hi,

Sometime i need to find logs for specific ip ranges. Wildcard (172.22.22.2*) works in most cases, but not all. 

What do you think of adding ip address converter to elasticsearche's ip type?

"properties" : {
  "clientip" : { "type": "ip"}
}

With this feature searching for ip ranges would be much easier and convenient. E.g. you could just set any range you want - clientip:[172.16.17.14 TO 172.23.17.78].
Wildcard searches are good, but they are pretty expensive and requires more resources.

regards,

**Comment by ion-storm** [comment]
yep, please add this

**Comment by joschi** [comment]
This is already possible today.

You'll have to create a custom index mapping in Elasticsearch which specifies the "ip" type for your custom field(s). After that, you can run range queries on that field.

**mapping.json**
```json
{
  "template": "graylog_*",
  "mappings" : {
    "message" : {
      "properties" : {
        "ip_addr" : {
          "type" : "ip"
        }
      }
    }
  }
}
```

**Add custom template to Elasticsearch**
```
$ curl -X PUT -d @'mapping.json' 'http://localhost:9200/_template/graylog-ip-mapping?pretty'
```
```json
{
  "acknowledged" : true
}
```

**Rotate active write index and check index mapping (via the deflector alias)**
```
$ curl 'http://localhost:9200/graylog_deflector/_mapping?pretty'
```
```json
{
  "graylog_1" : {
    "mappings" : {
      "message" : {
        "dynamic_templates" : [
          {
            "internal_fields" : {
              "match" : "gl2_*",
              "mapping" : {
                "type" : "keyword"
              }
            }
          },
          {
            "store_generic" : {
              "match" : "*",
              "mapping" : {
                "index" : "not_analyzed"
              }
            }
          }
        ],
        "properties" : {
          "full_message" : {
            "type" : "text",
            "analyzer" : "standard"
          },
          "ip_addr" : {
            "type" : "ip"
          },
          "message" : {
            "type" : "text",
            "analyzer" : "standard"
          },
          "source" : {
            "type" : "text",
            "analyzer" : "analyzer_keyword",
            "fielddata" : true
          },
          "streams" : {
            "type" : "keyword"
          },
          "timestamp" : {
            "type" : "date",
            "format" : "yyyy-MM-dd HH:mm:ss.SSS"
          }
        }
      }
    }
  }
}
```

**Example message (generated with a Random HTTP message generator and a randomly chosen IP address in the "ip_addr" field**
![Random message](https://user-images.githubusercontent.com/43951/36586674-f70dd01e-1882-11e8-949d-8b3f64199258.png)

Under this premise, the following queries are working as expected:
```text
ip_addr:203.0.113.0\/24
```
```text
ip_addr:"203.0.113.0/24"
```
```text
ip_addr:[203.0.113.0 TO 203.0.113.100]
```

The Graylog setup was created using Docker and Docker Compose with the following `docker-compose.yml` file:
```
version: '2'
services:
  mongo:
    image: mongo:3
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.7
    environment:
      - http.host=0.0.0.0
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    ports:
      - 9200:9200
  graylog:
    image: graylog/graylog:2.4.3-1
    environment:
      - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
      # Password: admin
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_WEB_ENDPOINT_URI=http://127.0.0.1:9000/api
      - GRAYLOG_MESSAGE_JOURNAL_ENABLED=false
    links:
      - mongo
      - elasticsearch
    ports:
      - 9000:9000
```
